rmmod buzzer.ko
rm /dev/buzzer
rmmod led.ko
rm /dev/led
rmmod led_alert.ko
rm /dev/led_alert
rmmod motor.ko
rm /dev/motor
rmmod water_pump.ko
rm /dev/water_pump
rmmod dht11.ko
rm /dev/dht11_dev
rmmod light_sensor.ko
rm /dev/light_sensor_dev
rmmod pir.ko
rm /dev/pir
rmmod soil_sensor.ko
rm /dev/soil_sensor_dev
rmmod ultrasonic.ko
rm /dev/ultrasonic_dev

